### ISSUE TITLE
后端网页失效

### ISSUE THREAD

**Issue by kirin-dev** [weingxing/Library-Seat-Reservation#1]
502 Bad Gateway
然后报错（因为小白，所以只知道一个原因，其它的不知道。。。请帮忙解决一下吧，谢谢了！）
‘主页’报错
![image](https://user-images.githubusercontent.com/71967844/107450096-9df48b00-6b7f-11eb-95e6-ef9c46adc057.png)
‘我的’报错
![image](https://user-images.githubusercontent.com/71967844/107450239-de540900-6b7f-11eb-89f6-9126efb4ee6f.png)
时间比较急……希望能尽快得到您的回复！大佬%%%

**Comment by weingxing** [comment]
小程序的utils/api.js 里的"https://test.mapletown.xyz"改成你自己部署的后端地址

**Comment by kirin-dev** [comment]
> 小程序的utils/api.js 里的"[https://test.mapletown.xyz"改成你自己部署的后端地址](https://test.mapletown.xyz%22%E6%94%B9%E6%88%90%E4%BD%A0%E8%87%AA%E5%B7%B1%E9%83%A8%E7%BD%B2%E7%9A%84%E5%90%8E%E7%AB%AF%E5%9C%B0%E5%9D%80)

我没有自己部署的后端...想通过您的学习一下...然后发现不能用了

**Comment by weingxing** [comment]
这个xian

> > 小程序的utils/api.js 里的"[https://test.mapletown.xyz"改成你自己部署的后端地址](https://test.mapletown.xyz%22%E6%94%B9%E6%88%90%E4%BD%A0%E8%87%AA%E5%B7%B1%E9%83%A8%E7%BD%B2%E7%9A%84%E5%90%8E%E7%AB%AF%E5%9C%B0%E5%9D%80)
> 
> 我没有自己部署的后端...想通过您的学习一下...然后发现不能用了

这个项目就是后端啊，你clone下来部署在本地就行，SpringBoot的项目部署很简单，然后那个地址改成 [http://localhost:端口号]()，小程序开发工具里面把域名校验关了就行了，test.mapletown.xyz是我之前在云端部署的，服务器资源有限，所以关了

**Comment by kirin-dev** [comment]
> 这个xian
> 
> > > 小程序的utils/api.js 里的"[https://test.mapletown.xyz"改成你自己部署的后端地址](https://test.mapletown.xyz%22%E6%94%B9%E6%88%90%E4%BD%A0%E8%87%AA%E5%B7%B1%E9%83%A8%E7%BD%B2%E7%9A%84%E5%90%8E%E7%AB%AF%E5%9C%B0%E5%9D%80)
> > 
> > 
> > 我没有自己部署的后端...想通过您的学习一下...然后发现不能用了
> 
> 这个项目就是后端啊，你clone下来部署在本地就行，SpringBoot的项目部署很简单，然后那个地址改成 http://localhost:端口号，小程序开发工具里面把域名校验关了就行了，test.mapletown.xyz是我之前在云端部署的，服务器资源有限，所以关了

我下载下来了，我也会改地址，但是怎么重新进行部署啊
在小程序转到‘我的’界面时还会报渲染层网络层错误

**Comment by weingxing** [comment]
后端你要运行起来啊，确保后端能访问，小程序才可以使用

**Comment by Kirin-dev** [comment]
emmm我这边显示：1. 程序包org.opencv不存在
2. 找不到符号
  符号:   类 Mat
  位置: 类 com.oxygen.face.util.OpenCVUtil

**Comment by weingxing** [comment]
看README文件，先配置OpenCV环境，要手动导入OpenCV的jar包

**Comment by kirin-dev** [comment]
经过您的指导，我目前能跑起来了
但是我添加了我的学号姓名之后，小程序登录端显示没有权限请联系管理员，这是什么原因呢？
然后请问在哪里可以把学号的长度改长两个字段呢？

**Comment by weingxing** [comment]
改长两个字段是学号长度不够？字段长度改数据库，没有权限，小程序绑定账号了吗，先在后台添加一个学号，然后小程序绑定这个学号

**Comment by weingxing** [comment]
方便的话留一下微信或者QQ，GitHub沟通不方便

**Comment by kirin-dev** [comment]
> 方便的话留一下微信或者QQ，GitHub沟通不方便

QQ：820781738
